import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'english' | 'tamil' | 'hindi' | 'telugu' | 'kannada';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
  getLanguageOptions: () => { value: Language; label: string; nativeLabel: string }[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  english: {
    company_name: 'HARVTECH',
    tagline: 'Empowering Farmers, Connecting Markets',
    login: 'Login',
    register: 'Register',
    help: 'Help',
    welcome_back: 'Welcome Back!',
    mobile_number: 'Mobile Number',
    send_otp: 'Send OTP',
    enter_otp: 'Enter OTP',
    verify_otp: 'Verify OTP',
    select_role: 'Select Your Role',
    role_question: 'Are you an Owner or a User?',
    role_description: 'Choose your role to continue with registration',
    owner: 'Owner',
    user: 'User',
    owner_desc: 'I own agricultural equipment',
    user_desc: 'I want to lease equipment',
    user_registration: 'User Registration',
    owner_registration: 'Owner Registration',
    full_name: 'Full Name',
    city: 'City',
    country: 'Country',
    aadhaar_number: 'Aadhaar Number',
    terms_agreement: 'I agree to the Terms and Conditions and Privacy Policy',
    select_equipment: 'Select Your Equipment',
    tractor: 'Tractor',
    weeder: 'Weeder',
    tiller: 'Tiller',
    model_number: 'Model Number',
    chassis_vin: 'Chassis No. / VIN',
    continue: 'Continue',
    welcome: 'Welcome,',
    farmer_id: 'Farmer ID',
    machine_lease: 'Machine Lease',
    platforms: 'Platforms',
    services: 'Services',
    power: 'Power',
    location: 'Location',
    availability: 'Availability',
    per_day: 'per day',
    select: 'Select',
    payment: 'Payment',
    order_summary: 'Order Summary',
    equipment: 'Equipment',
    duration: 'Duration',
    rental_cost: 'Rental Cost',
    security_deposit: 'Security Deposit',
    total: 'Total',
    scan_qr: 'Scan QR Code to Pay',
    payment_instruction: 'Use any UPI app to scan and pay',
    confirm_payment: 'Confirm Payment',
    success: 'Success!',
    your_farmer_id: 'Your Farmer ID',
    ok: 'OK',
    model: 'Model',
    year: 'Year',
    chassis_no: 'Chassis No',
    status: 'Status',
    platform: 'Platform',
    cancel: 'Cancel',
    accept: 'Accept',
    view_terms: 'View Terms & Conditions',
    terms_and_conditions: 'Terms and Conditions',
    otp_verification: 'OTP Verification',
    otp_sent_to: 'OTP sent to your mobile number',
    resend_otp: 'Resend OTP',
    booking_type: 'Booking Type',
    advance_amount: 'Advance Payment',
    my_bookings: 'My Bookings',
    booked_equipment: 'Booked Equipment',
    booking_status: 'Status',
    advance_paid: 'Advance Paid',
    pending_pickup: 'Pending Pickup',
    in_use: 'In Use',
    returned: 'Returned',
    government_schemes: 'Government Schemes',
    my_equipment: 'My Equipment',
    equipment_leasing: 'Equipment Leasing',
    lease_my_equipment: 'Lease My Equipment',
  },
  tamil: {
    company_name: 'ஹார்வ்டெக்',
    tagline: 'விவசாயிகளை வலுப்படுத்துதல், சந்தைகளை இணைத்தல்',
    login: 'உள்நுழைவு',
    register: 'பதிவு செய்யவும்',
    help: 'உதவி',
    welcome_back: 'மீண்டும் வரவேற்கிறோம்!',
    mobile_number: 'கைபேசி எண்',
    send_otp: 'OTP அனுப்பவும்',
    enter_otp: 'OTP உள்ளிடவும்',
    verify_otp: 'OTP சரிபார்க்கவும்',
    select_role: 'உங்கள் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
    role_question: 'நீங்கள் உரிமையாளரா அல்லது பயனரா?',
    role_description: 'பதிவுசெய்ய தொடர உங்கள் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
    owner: 'உரிமையாளர்',
    user: 'பயனர்',
    owner_desc: 'என்னிடம் விவசாய கருவிகள் உள்ளன',
    user_desc: 'நான் கருவிகளை குத்தகைக்கு எடுக்க விரும்புகிறேன்',
    user_registration: 'பயனர் பதிவு',
    owner_registration: 'உரிமையாளர் பதிவு',
    full_name: 'முழு பெயர்',
    city: 'நகரம்',
    country: 'நாடு',
    aadhaar_number: 'ஆதார் எண்',
    terms_agreement: 'நிபந்தனைகள் மற்றும் தனியுரிமைக் கொள்கையை ஒப்புக்கொள்கிறேன்',
    select_equipment: 'உங்கள் கருவியைத் தேர்ந்தெடுக்கவும்',
    tractor: 'டிராக்டர்',
    weeder: 'களை நீக்கி',
    tiller: 'உழவர்',
    model_number: 'மாடல் எண்',
    chassis_vin: 'சேஸிஸ் எண் / VIN',
    continue: 'தொடரவும்',
    welcome: 'வரவேற்கிறோம்,',
    farmer_id: 'விவசாயி ID',
    machine_lease: 'இயந்திர குத்தகை',
    platforms: 'தளங்கள்',
    services: 'சேவைகள்',
    power: 'சக்தி',
    location: 'இடம்',
    availability: 'கிடைக்கும் தன்மை',
    per_day: 'ஒரு நாளைக்கு',
    select: 'தேர்ந்தெடுக்கவும்',
    payment: 'கட்டணம்',
    order_summary: 'ஆர்டர் சுருக்கம்',
    equipment: 'கருவி',
    duration: 'காலம்',
    rental_cost: 'வாடகை செலவு',
    security_deposit: 'பாதுகாப்பு வைப்பு',
    total: 'மொத்தம்',
    scan_qr: 'கட்டணம் செலுத்த QR குறியீட்டை ஸ்கேன் செய்யவும்',
    payment_instruction: 'ஸ்கேன் செய்து கட்டணம் செலுத்த எந்த UPI ஆப்பையும் பயன்படுத்தவும்',
    confirm_payment: 'கட்டணத்தை உறுதிப்படுத்தவும்',
    success: 'வெற்றி!',
    your_farmer_id: 'உங்கள் விவசாயி ID',
    ok: 'சரி',
    model: 'மாடல்',
    year: 'ஆண்டு',
    chassis_no: 'சேஸிஸ் எண்',
    status: 'நிலை',
    platform: 'தளம்',
    cancel: 'ரத்து செய்',
    accept: 'ஏற்க',
    view_terms: 'விதிமுறைகள் மற்றும் நிபந்தனைகளைப் பார்க்கவும்',
    terms_and_conditions: 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
    otp_verification: 'OTP சரிபார்ப்பு',
    otp_sent_to: 'உங்கள் மொபைல் எண்ணுக்கு OTP அனுப்பப்பட்டது',
    resend_otp: 'OTP மீண்டும் அனுப்பவும்',
    booking_type: 'முன்பதிவு வகை',
    advance_amount: 'முன்பணம்',
    my_bookings: 'என் முன்பதிவுகள்',
    booked_equipment: 'முன்பதிவு செய்த கருவிகள்',
    booking_status: 'நிலை',
    advance_paid: 'முன்பணம் செலுத்தியது',
    pending_pickup: 'எடுக்க காத்திருக்கிறது',
    in_use: 'பயன்பாட்டில்',
    returned: 'திரும்பியது',
    government_schemes: 'அரசு திட்டங்கள்',
    my_equipment: 'எனது கருவிகள்',
    equipment_leasing: 'கருவி குத்தகை',
    lease_my_equipment: 'எனது கருவியை குத்தகைக்கு கொடு',
  },
  hindi: {
    company_name: 'हार्वटेक',
    tagline: 'किसानों को सशक्त बनाना, बाजारों को जोड़ना',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    help: 'सहायता',
    welcome_back: 'वापसी पर स्वागत है!',
    mobile_number: 'मोबाइल नंबर',
    send_otp: 'OTP भेजें',
    enter_otp: 'OTP दर्ज करें',
    verify_otp: 'OTP सत्यापित करें',
    select_role: 'अपनी भूमिका चुनें',
    role_question: 'क्या आप मालिक हैं या उपयोगकर्ता?',
    role_description: 'पंजीकरण जारी रखने के लिए अपनी भूमिका चुनें',
    owner: 'मालिक',
    user: 'उपयोगकर्ता',
    owner_desc: 'मेरे पास कृषि उपकरण हैं',
    user_desc: 'मैं उपकरण किराए पर लेना चाहता हूं',
    user_registration: 'उपयोगकर्ता पंजीकरण',
    owner_registration: 'मालिक पंजीकरण',
    full_name: 'पूरा नाम',
    city: 'शहर',
    country: 'देश',
    aadhaar_number: 'आधार नंबर',
    terms_agreement: 'मैं नियम और शर्तों और गोपनीयता नीति से सहमत हूं',
    select_equipment: 'अपना उपकरण चुनें',
    tractor: 'ट्रैक्टर',
    weeder: 'खरपतवार हटाने वाला',
    tiller: 'जुताई मशीन',
    model_number: 'मॉडल नंबर',
    chassis_vin: 'चेसिस नं. / VIN',
    continue: 'जारी रखें',
    welcome: 'स्वागत है,',
    farmer_id: 'किसान ID',
    machine_lease: 'मशीन किराया',
    platforms: 'प्लेटफॉर्म',
    services: 'सेवाएं',
    power: 'शक्ति',
    location: 'स्थान',
    availability: 'उपलब्धता',
    per_day: 'प्रति दिन',
    select: 'चुनें',
    payment: 'भुगतान',
    order_summary: 'ऑर्डर सारांश',
    equipment: 'उपकरण',
    duration: 'अवधि',
    rental_cost: 'किराया लागत',
    security_deposit: 'सिक्यूरिटी डिपॉजिट',
    total: 'कुल',
    scan_qr: 'भुगतान के लिए QR कोड स्कैन करें',
    payment_instruction: 'स्कैन करने और भुगतान के लिए किसी भी UPI ऐप का उपयोग करें',
    confirm_payment: 'भुगतान की पुष्टि करें',
    success: 'सफलता!',
    your_farmer_id: 'आपका किसान ID',
    ok: 'ठीक है',
    model: 'मॉडल',
    year: 'वर्ष',
    chassis_no: 'चेसिस नं.',
    status: 'स्थिति',
    platform: 'प्लेटफॉर्म',
    cancel: 'रद्द करें',
    accept: 'स्वीकार करें',
    view_terms: 'नियम और शर्तें देखें',
    terms_and_conditions: 'नियम और शर्तें',
    otp_verification: 'OTP सत्यापन',
    otp_sent_to: 'आपके मोबाइल नंबर पर OTP भेजा गया',
    resend_otp: 'OTP फिर से भेजें',
    booking_type: 'बुकिंग प्रकार',
    advance_amount: 'अग्रिम भुगतान',
    my_bookings: 'मेरी बुकिंग',
    booked_equipment: 'बुक किया गया उपकरण',
    booking_status: 'स्थिति',
    advance_paid: 'अग्रिम भुगतान',
    pending_pickup: 'पिकअप लंबित',
    in_use: 'उपयोग में',
    returned: 'वापस किया गया',
    government_schemes: 'सरकारी योजनाएं',
    my_equipment: 'मेरे उपकरण',
    equipment_leasing: 'उपकरण किराया',
    lease_my_equipment: 'मेरे उपकरण को किराए पर दें',
  },
  telugu: {
    company_name: 'హార్వ్‌టెక్',
    tagline: 'రైతులను బలపర్చడం, మార్కెట్లను అనుసంధానించడం',
    login: 'లాగిన్',
    register: 'రిజిస్టర్',
    help: 'సహాయం',
    welcome_back: 'తిరిగి స్వాగతం!',
    mobile_number: 'మొబైల్ నంబర్',
    send_otp: 'OTP పంపండి',
    enter_otp: 'OTP ఎంటర్ చేయండి',
    verify_otp: 'OTP వేరిఫై చేయండి',
    select_role: 'మీ పాత్రను ఎంచుకోండి',
    role_question: 'మీరు యజమానివా లేక వినియోగదారువా?',
    role_description: 'రిజిస్ట్రేషన్ కొనసాగించడానికి మీ పాత్రను ఎంచుకోండి',
    owner: 'యజమాని',
    user: 'వినియోగదారు',
    owner_desc: 'నా దగ్గర వ్యవసాయ పరికరాలు ఉన్నాయి',
    user_desc: 'నేను పరికరాలను అద్దెకు తీసుకోవాలనుకుంటున్నాను',
    user_registration: 'వినియోగదారు రిజిస్ట్రేషన్',
    owner_registration: 'యజమాని రిజిస్ట్రేషన్',
    full_name: 'పూర్తి పేరు',
    city: 'నగరం',
    country: 'దేశం',
    aadhaar_number: 'ఆధార్ నంబర్',
    terms_agreement: 'నేను నిబంధనలు మరియు షరతులు మరియు గోప్యతా విధానానికి అంగీకరిస్తున్నాను',
    select_equipment: 'మీ పరికరాన్ని ఎంచుకోండి',
    tractor: 'ట్రాక్టర్',
    weeder: 'కలుపు తీసేది',
    tiller: 'కర్షకుడు',
    model_number: 'మోడల్ నంబర్',
    chassis_vin: 'చాసిస్ నం. / VIN',
    continue: 'కొనసాగించు',
    welcome: 'స్వాగతం,',
    farmer_id: 'రైతు ID',
    machine_lease: 'మెషిన్ లీజ్',
    platforms: 'ప్లాట్‌ఫారమ్‌లు',
    services: 'సేవలు',
    power: 'శక్తి',
    location: 'స్థానం',
    availability: 'లభ్యత',
    per_day: 'రోజుకు',
    select: 'ఎంచుకోండి',
    payment: 'చెల్లింపు',
    order_summary: 'ఆర్డర్ సారాంశం',
    equipment: 'పరికరం',
    duration: 'వ్యవధి',
    rental_cost: 'అద్దె ఖర్చు',
    security_deposit: 'భద్రతా డిపాజిట్',
    total: 'మొత్తం',
    scan_qr: 'చెల్లించడానికి QR కోడ్‌ను స్కాన్ చేయండి',
    payment_instruction: 'స్కాన్ చేసి చెల్లించడానికి ఏదైనా UPI యాప్‌ను ఉపయోగించండి',
    confirm_payment: 'చెల్లింపును నిర్ధారించండి',
    success: 'విజయం!',
    your_farmer_id: 'మీ రైతు ID',
    ok: 'సరే',
    model: 'మోడల్',
    year: 'సంవత్సరం',
    chassis_no: 'చాసిస్ నం.',
    status: 'స్థితి',
    platform: 'ప్లాట్‌ఫారమ్',
    cancel: 'రద్దు చేయు',
    accept: 'అంగీకరించు',
    view_terms: 'నిబంధనలు మరియు షరతులను చూడండి',
    terms_and_conditions: 'నిబంధనలు మరియు షరతులు',
    otp_verification: 'OTP ధృవీకరణ',
    otp_sent_to: 'మీ మొబైల్ నంబర్‌కు OTP పంపబడింది',
    resend_otp: 'OTP మళ్లీ పంపండి',
    booking_type: 'బుకింగ్ రకం',
    advance_amount: 'ముందస్తు చెల్లింపు',
    my_bookings: 'నా బుకింగ్‌లు',
    booked_equipment: 'బుక్ చేయబడిన పరికరం',
    booking_status: 'స్థితి',
    advance_paid: 'ముందస్తు చెల్లింపు',
    pending_pickup: 'పికప్ పెండింగ్',
    in_use: 'వాడుకలో',
    returned: 'తిరిగి ఇవ్వబడింది',
    government_schemes: 'ప్రభుత్వ పథకాలు',
    my_equipment: 'నా పరికరాలు',
    equipment_leasing: 'పరికర లీజింగ్',
    lease_my_equipment: 'నా పరికరాన్ని లీజుకు ఇవ్వండి',
  },
  kannada: {
    company_name: 'ಹಾರ್ವ್‌ಟೆಕ್',
    tagline: 'ರೈತರನ್ನು ಸಬಲೀಕರಿಸುವುದು, ಮಾರುಕಟ್ಟೆಗಳನ್ನು ಸಂಪರ್ಕಿಸುವುದು',
    login: 'ಲಾಗಿನ್',
    register: 'ನೋಂದಣಿ',
    help: 'ಸಹಾಯ',
    welcome_back: 'ಮತ್ತೆ ಸ್ವಾಗತ!',
    mobile_number: 'ಮೊಬೈಲ್ ನಂಬರ್',
    send_otp: 'OTP ಕಳುಹಿಸಿ',
    enter_otp: 'OTP ನಮೂದಿಸಿ',
    verify_otp: 'OTP ಪರಿಶೀಲಿಸಿ',
    select_role: 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    role_question: 'ನೀವು ಮಾಲೀಕರೋ ಅಥವಾ ಬಳಕೆದಾರರೋ?',
    role_description: 'ನೋಂದಣಿ ಮುಂದುವರಿಸಲು ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    owner: 'ಮಾಲೀಕ',
    user: 'ಬಳಕೆದಾರ',
    owner_desc: 'ನನ್ನ ಬಳಿ ಕೃಷಿ ಉಪಕರಣಗಳಿವೆ',
    user_desc: 'ನಾನು ಉಪಕರಣಗಳನ್ನು ಬಾಡಿಗೆಗೆ ತೆಗೆದುಕೊಳ್ಳಲು ಬಯಸುತ್ತೇನೆ',
    user_registration: 'ಬಳಕೆದಾರ ನೋಂದಣಿ',
    owner_registration: 'ಮಾಲೀಕ ನೋಂದಣಿ',
    full_name: 'ಪೂರ್ಣ ಹೆಸರು',
    city: 'ನಗರ',
    country: 'ದೇಶ',
    aadhaar_number: 'ಆಧಾರ್ ಸಂಖ್ಯೆ',
    terms_agreement: 'ನಾನು ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು ಮತ್ತು ಗೌಪ್ಯತೆ ನೀತಿಯನ್ನು ಒಪ್ಪುತ್ತೇನೆ',
    select_equipment: 'ನಿಮ್ಮ ಉಪಕರಣವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    tractor: 'ಟ್ರಾಕ್ಟರ್',
    weeder: 'ಕಳೆ ತೆಗೆಯುವವನು',
    tiller: 'ಉಳುವವನು',
    model_number: 'ಮಾಡಲ್ ನಂಬರ್',
    chassis_vin: 'ಚಾಸಿಸ್ ಸಂ. / VIN',
    continue: 'ಮುಂದುವರಿಸಿ',
    welcome: 'ಸ್ವಾಗತ,',
    farmer_id: 'ರೈತ ID',
    machine_lease: 'ಯಂತ್ರ ಗುತ್ತಿಗೆ',
    platforms: 'ವೇದಿಕೆಗಳು',
    services: 'ಸೇವೆಗಳು',
    power: 'ಶಕ್ತಿ',
    location: 'ಸ್ಥಳ',
    availability: 'ಲಭ್ಯತೆ',
    per_day: 'ದಿನಕ್ಕೆ',
    select: 'ಆಯ್ಕೆಮಾಡಿ',
    payment: 'ಪಾವತಿ',
    order_summary: 'ಆರ್ಡರ್ ಸಾರಾಂಶ',
    equipment: 'ಉಪಕರಣ',
    duration: 'ಅವಧಿ',
    rental_cost: 'ಬಾಡಿಗೆ ವೆಚ್ಚ',
    security_deposit: 'ಭದ್ರತಾ ಠೇವಣಿ',
    total: 'ಒಟ್ಟು',
    scan_qr: 'ಪಾವತಿ ಮಾಡಲು QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    payment_instruction: 'ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಪಾವತಿ ಮಾಡಲು ಯಾವುದೇ UPI ಅಪ್ಲಿಕೇಶನ್ ಬಳಸಿ',
    confirm_payment: 'ಪಾವತಿಯನ್ನು ದೃಢೀಕರಿಸಿ',
    success: 'ಯಶಸ್ಸು!',
    your_farmer_id: 'ನಿಮ್ಮ ರೈತ ID',
    ok: 'ಸರಿ',
    model: 'ಮಾಡಲ್',
    year: 'ವರ್ಷ',
    chassis_no: 'ಚಾಸಿಸ್ ಸಂ.',
    status: 'ಸ್ಥಿತಿ',
    platform: 'ವೇದಿಕೆ',
    cancel: 'ರದ್ದುಮಾಡು',
    accept: 'ಒಪ್ಪಿಕೊಳ್ಳು',
    view_terms: 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    terms_and_conditions: 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
    otp_verification: 'OTP ಪರಿಶೀಲನೆ',
    otp_sent_to: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ OTP ಕಳುಹಿಸಲಾಗಿದೆ',
    resend_otp: 'OTP ಮತ್ತೆ ಕಳುಹಿಸಿ',
    booking_type: 'ಬುಕಿಂಗ್ ಪ್ರಕಾರ',
    advance_amount: 'ಮುಂಗಡ ಪಾವತಿ',
    my_bookings: 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
    booked_equipment: 'ಬುಕ್ ಮಾಡಿದ ಉಪಕರಣ',
    booking_status: 'ಸ್ಥಿತಿ',
    advance_paid: 'ಮುಂಗಡ ಪಾವತಿ',
    pending_pickup: 'ಪಿಕಪ್ ಬಾಕಿ',
    in_use: 'ಬಳಕೆಯಲ್ಲಿ',
    returned: 'ಹಿಂತಿರುಗಿಸಲಾಗಿದೆ',
    government_schemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    my_equipment: 'ನನ್ನ ಉಪಕರಣಗಳು',
    equipment_leasing: 'ಉಪಕರಣ ಗುತ್ತಿಗೆ',
    lease_my_equipment: 'ನನ್ನ ಉಪಕರಣವನ್ನು ಗುತ್ತಿಗೆಗೆ ಕೊಡಿ',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('english');

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
  };

  const getLanguageOptions = () => [
    { value: 'english' as Language, label: 'English', nativeLabel: 'English' },
    { value: 'tamil' as Language, label: 'Tamil', nativeLabel: 'தமிழ்' },
    { value: 'hindi' as Language, label: 'Hindi', nativeLabel: 'हिंदी' },
    { value: 'telugu' as Language, label: 'Telugu', nativeLabel: 'తెలుగు' },
    { value: 'kannada' as Language, label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
  ];

  const t = (key: string): string => {
    return translations[currentLanguage][key as keyof typeof translations.english] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, getLanguageOptions }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
